using System.ComponentModel.DataAnnotations.Schema;
using Application.Extensions;
using FastEndpoints;

namespace Application.Jobs;

/*
var trackingId = await command.QueueJobAsync(jobRecord =>
{
    jobRecord.CreatedOn = DateTime.UtcNow;
    jobRecord.CreatedByUserId = "user";
    jobRecord.CreatedByDisplayName = "User Name";
});
*/

public sealed class JobRecord : IJobStorageRecord, IJobResultStorage
{
  // required by IJobStorageRecord
  /// <summary>
  /// a unique id for the job queue. each command type has its own queue. this is automatically generated by the library.
  /// </summary>
  public string QueueID { get; set; } = default!;

  // required by IJobStorageRecord
  /// <summary>
  /// a unique id used to track a particular job for the purpose of progress monitoring and/or termination.
  /// </summary>
  public Guid TrackingID { get; set; } = default!;

  // required by IJobStorageRecord
  /// <summary>
  /// Uses WorkCommandJson for storage instead
  /// </summary>
  [NotMapped]
  public object Command { get; set; } = default!;

  /// <summary>
  /// Serlialized Command JSON Node for storage
  /// </summary>
  public string WorkCommandJson { get; set; } = default!;

  // required by IJobResultStorage
  /// <summary>
  /// Uses WorkResultJson for storage instead
  /// </summary>
  [NotMapped]
  public object? Result { get; set; } = default!;

  /// <summary>
  /// Result Record
  /// </summary>
  public string? WorkResultJson { get; set; } = default!;

  /// <summary>
  /// Log of items as newline separated JSON
  /// </summary>
  public string WorkLogJsonLines { get; set; } = string.Empty;

  /// <summary>
  /// the number of tries made.
  /// </summary>
  public int Tries { get; set; } = 0;

  // required by IJobStorageRecord
  /// <summary>
  /// the job will not be executed before this date/time. by default, it will automatically be set to the time of creation allowing jobs to be executed as soon as they're
  /// created.
  /// </summary>
  public DateTime ExecuteAfter { get; set; }

  // required by IJobStorageRecord
  /// <summary>
  /// the expiration date/time of job. if the job remains in an incomplete state past this time, the record is considered stale, and will be marked for removal from
  /// storage.
  /// </summary>
  public DateTime ExpireOn { get; set; }

  // required by IJobStorageRecord
  /// <summary>
  /// indicates whether the job has successfully completed or not.
  /// </summary>
  public bool IsComplete { get; set; }

  /// <summary>
  /// Indicates whether the job has been cancelled
  /// </summary>
  public bool IsCancelled { get; set; }

  /// <summary>
  /// the date/time when the job started processing.
  /// </summary>
  public DateTime? StartedOn { get; set; }

  /// <summary>
  /// the date/time when the job finished processing.
  /// </summary>
  public DateTime? FinishedOn { get; set; }

  /// <summary>
  /// the date/time when the job record was created.
  /// </summary>
  public DateTime CreatedOn { get; set; } = DateTime.UtcNow;

  /// <summary>
  /// the user id of the user who created the job record.
  /// </summary>
  public string CreatedByUserId { get; set; } = "SYSTEM";

  /// <summary>
  /// the display name of the user who created the job record.
  /// </summary>
  public string CreatedByDisplayName { get; set; } = "System";


  // Used for deserializing the concrete command object
  public TCommand GetCommand<TCommand>() where TCommand : class, ICommandBase
  {
    return JsonHelper.FromJson<TCommand>(WorkCommandJson)!;
  }

  // Used for serializing the concrete command object
  public void SetCommand<TCommand>(TCommand command) where TCommand : class, ICommandBase
  {
    WorkCommandJson = JsonHelper.ToJson(command);
  }

  /// <summary>
  /// implement this function to customize the result deserialization.
  /// </summary>
  public TResult? GetResult<TResult>()
  {
    return string.IsNullOrWhiteSpace(WorkResultJson) ? default : JsonHelper.FromJson<TResult>(WorkResultJson);
  }

  /// <summary>
  /// implement this method to customize the result serialization.
  /// </summary>
  public void SetResult<TResult>(TResult result)
  {
    WorkResultJson = JsonHelper.ToJson(result);
  }
}
